<span style="font-weight: bold;"><br>
<br>
</span>

<p>
<br>

<table style="text-align: left; width: 100%;" border="0" cellpadding="0" cellspacing="0">
<tbody>
<tr>
<td><a href="http://www.springer.com/statistics/life+sciences%2C+medicine+%26+health/book/978-1-4614-7617-7"><img style="border: 0px solid ; width: 201px; height: 300px;" alt="book cover" title="Applied Spatial Data Analysis with R" src="cover-2ed.jpg"></a></td>
<td><span style="font-weight: bold;">Applied
Spatial Data Analysis with R<br>
<br>
</span>Roger S. Bivand, Edzer Pebesma and V. G&oacute;mez-Rubio<br>
<br>
UseR! Series, Springer<br>
<br>
2nd ed. 2013,  xviii+405 pp., Softcover<br>
<br>
ISBN: 978-1-4614-7617-7<br>
<br>
<br>
<br>
<span style="font-weight: bold;"></span></td>
</tr>
<tr>
<td><a href="http://www.springer.com/978-0-387-78170-9"><img style="border: 0px solid ; width: 240px; height: 240px;" alt="book cover" title="Applied Spatial Data Analysis with R" src="cover2.jpg"></a></td>
<td><span style="font-weight: bold;">Applied
Spatial Data Analysis with R<br>
<br>
</span>Roger S. Bivand, Edzer J. Pebesma and V. G&oacute;mez-Rubio<br>
<br>
UseR! Series, Springer<br>
<br>
2008, 378 p., Softcover<br>
<br>
ISBN: 978-0-387-78170-9<br>
<br>
<br>
<br>
<span style="font-weight: bold;"></span></td>
</tr>
</tbody>
</table>
<span style="font-weight: bold;"><br>
<br>
<br>
</span>
<h2>Resources</h2>
<ul>
<li>Some links to <a href="http://www.asdar-book.org/courses.php">course materials</a></li>
<li>Code and data download by chapter (2nd ed.)</li>
<li>Book figures by chapter (1st ed.)</li>
<li>Code download by chapter (1st ed.)</li>
<li>Data sets download (1st ed.)</li>
<li>Additional materials, including code for running examples depending on external software, such as WinBUGS, GRASS, and ArcGIS (1st ed.)</li>
</ul>
<h2><span style="font-weight: bold;">Authors</span></h2>
<span style="font-weight: bold;">Roger S. Bivand</span>
is Professor of Geography in the Department of Economics
at Norwegian School of Economics, Bergen, Norway. <br>
<br>
<span style="font-weight: bold;">Edzer Pebesma</span>
is Professor
of Geoinformatics at Westf&auml;lische Wilhelms-Universit&auml;t, M&uuml;nster,
Germany. <br>
<br>
<span style="font-weight: bold;">Virgilio G&oacute;mez-Rubio</span>
is Associate Professor in the Department of Mathematics at Universidad 
de Castilla-La Mancha, Albacete, Spain.
